---
services:
  redis:
    host: 192.168.1.2
    port: 6379

tempsensors:
  loft:
    host: 192.168.1.2
    hardwareid: 28-0315a1d259ff
    name: Loft
  hotwaterflow:
    host: 192.168.1.12
    hardwareid: 28-0315a1b006ff
    name: Hot Water Flow
  hotwaterreturn:
    host: 192.168.1.12
    hardwareid: 28-0315a1d21dff
    name: Hot Water Return
  heatingflow:
    host: 192.168.1.12
    hardwareid: 28-0315a1b011ff
    name: Central Heating Flow
  heatingreturn:
    host: 192.168.1.12
    hardwareid: 28-0315a1b026ff
    name: Central Heating Return
  livingroom:
    host: 192.168.1.12
    hardwareid: 28-0415a187aaff
    name: Living Room
  test:
    host: 192.168.1.193
    hardwareid: 28-0315a1d297ff
    name: Test Probe
  hotwatertanktop:
    host: 192.168.1.2
    hardwareid: 28-0415a1ca05ff
    name: Hot Water Tank Top
  hotwatertankmiddle:
    host: 192.168.1.2
    hardwareid: 28-0415a18b42ff
    name: Hot Water Tank Middle
  hotwatertankbottom:
    host: 192.168.1.2
    hardwareid: 28-0415a18739ff
    name: Hot Water Tank Bottom

controls:
  hotwater:
    host: 192.168.1.12
    controlpin: 14
    name: Hot Water
    reversed: true
    statuspin: 18
  centralheatingpump:
    host: 192.168.1.12
    controlpin: 15
    name: Central Heating
    dependsupon: hotwater
    reversed: true
    statuspin: 17    
  landinglight:
    host: 192.168.1.12
    controlpin: 21
    name: Landing Light

switches:
  hosts:
    testpi:
      testswitch:
        controlpin: 17
        control: landinglight
      testswitch2:
        controlpin: 18
        control: testlight2



