---
tempsensors:
  understairs:
    host: 192.168.1.12
    id: 28-00145311e6ff
    friendlyname: Under the Stairs

controls:
  hotwater:
    host: 192.168.1.12
    gpio: 14
    friendlyname: Hot Water
    reversed: true
    statusgpio: 18
  centralheatingpump:
    host: 192.168.1.12
    gpio: 15
    friendlyname: Central Heating
    dependsupon: hotwater
    reversed: true
    statusgpio: 17    
  landinglight:
    host: 192.168.1.12
    gpio: 21
    friendlyname: Landing Light


